name: Build and Deploy Flask App on EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir flask

      - name: Build Docker image
        run: |
          docker build -t flask-app .

      - name: Run on EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_B64 }}
          USER: ${{ secrets.EC2_USER }}
          HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "${PRIVATE_KEY}" | base64 --decode > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "
            docker stop testing_docker || true &&
            docker rm testing_docker || true &&
            docker run -d --name testing_docker -p 5000:5000 585008042069.dkr.ecr.eu-north-1.amazonaws.com/testing_docker:latest 
          "